// <auto-generated />
using System;
using InfrastructureFMSDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfrastructureFMSDB.Migrations
{
    [DbContext(typeof(FMSDataContext))]
    partial class FMSDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("CoreFMS.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("CoreFMS.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAnonym")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CoreFMS.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CoreFMS.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Iso3")
                        .HasColumnType("longtext");

                    b.Property<string>("Nicename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short?>("Numcode")
                        .HasColumnType("smallint");

                    b.Property<int>("Phonecode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("CoreFMS.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EducationName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("CoreFMS.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DirectedToEmployeeId")
                        .HasColumnType("int(11)");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int(11)");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("IsAnonym")
                        .HasColumnType("int(1)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsChecked")
                        .HasColumnType("int(1)");

                    b.Property<int>("IsReplied")
                        .HasColumnType("int(1)");

                    b.Property<int>("IsSolved")
                        .HasColumnType("int(1)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int(5)");

                    b.Property<int?>("Shared")
                        .HasColumnType("int(11)");

                    b.Property<int?>("SubTypeId")
                        .HasColumnType("int(5)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int(5)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "CompanyId" }, "fk_feedback_company");

                    b.HasIndex(new[] { "DirectedToEmployeeId" }, "fk_feedback_companyEmployee");

                    b.HasIndex(new[] { "SubTypeId" }, "fk_feedback_feedbackSubType");

                    b.HasIndex(new[] { "TypeId" }, "fk_feedback_feedbackType");

                    b.HasIndex(new[] { "ProductId" }, "fk_feedback_product");

                    b.HasIndex(new[] { "SectorId" }, "fk_feedback_sector");

                    b.HasIndex(new[] { "UserId" }, "fk_feedback_user");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("CoreFMS.Entities.FeedbackSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FeedbackSubType");
                });

            modelBuilder.Entity("CoreFMS.Entities.FeedbackType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FeedbackType");
                });

            modelBuilder.Entity("CoreFMS.Entities.OperationMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OperationMode");
                });

            modelBuilder.Entity("CoreFMS.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CoreFMS.Entities.ReactionComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sentiment")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ReactionComment");
                });

            modelBuilder.Entity("CoreFMS.Entities.ReactionFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sentiment")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("ReactionFeedback");
                });

            modelBuilder.Entity("CoreFMS.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("CoreFMS.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("Id_UNIQUE1");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CoreFMS.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("CoreFMS.Entities.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int(11)");

                    b.Property<int>("SocialMediaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("SocialMediaId");

                    b.HasIndex("UserId");

                    b.ToTable("Share");
                });

            modelBuilder.Entity("CoreFMS.Entities.SocialMedium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SocialMediaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SocialMedia");
                });

            modelBuilder.Entity("CoreFMS.Entities.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SystemVariable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("System");
                });

            modelBuilder.Entity("CoreFMS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CityId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("FailedLoginAttemptCount")
                        .HasColumnType("int(3)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("IsTwoFactorAuth")
                        .HasColumnType("int(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Phone")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("PhoneCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'2'");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("Id_UNIQUE2");

                    b.HasIndex(new[] { "RoleId" }, "RoleId");

                    b.HasIndex(new[] { "CityId" }, "fk_user_city");

                    b.HasIndex(new[] { "CompanyId" }, "fk_user_company");

                    b.HasIndex(new[] { "EducationId" }, "fk_user_education");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.City", b =>
                {
                    b.HasOne("CoreFMS.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CoreFMS.Entities.Comment", b =>
                {
                    b.HasOne("CoreFMS.Entities.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.Comment", "ParentComment")
                        .WithMany("ChildComment")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.Company", b =>
                {
                    b.HasOne("CoreFMS.Entities.Sector", "Sector")
                        .WithMany("Companies")
                        .HasForeignKey("SectorId");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("CoreFMS.Entities.Feedback", b =>
                {
                    b.HasOne("CoreFMS.Entities.Company", "Company")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_feedback_company");

                    b.HasOne("CoreFMS.Entities.User", "DirectedCompanyEmployee")
                        .WithMany("DirectedFeedbacks")
                        .HasForeignKey("DirectedToEmployeeId")
                        .HasConstraintName("fk_feedback_companyEmployee");

                    b.HasOne("CoreFMS.Entities.Product", "Product")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_feedback_product");

                    b.HasOne("CoreFMS.Entities.Sector", "Sector")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SectorId")
                        .HasConstraintName("fk_feedback_sector");

                    b.HasOne("CoreFMS.Entities.FeedbackSubType", "SubType")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SubTypeId")
                        .HasConstraintName("fk_feedback_feedbackSubType");

                    b.HasOne("CoreFMS.Entities.FeedbackType", "Type")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_feedback_feedbackType")
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_feedback_user")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DirectedCompanyEmployee");

                    b.Navigation("Product");

                    b.Navigation("Sector");

                    b.Navigation("SubType");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.Product", b =>
                {
                    b.HasOne("CoreFMS.Entities.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CoreFMS.Entities.ReactionComment", b =>
                {
                    b.HasOne("CoreFMS.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.ReactionFeedback", b =>
                {
                    b.HasOne("CoreFMS.Entities.Feedback", "Feedback")
                        .WithMany("Reactions")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.Reply", b =>
                {
                    b.HasOne("CoreFMS.Entities.Feedback", "Feedback")
                        .WithMany("Reply")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.Share", b =>
                {
                    b.HasOne("CoreFMS.Entities.Feedback", "Feedback")
                        .WithMany("Shares")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.SocialMedium", "SocialMedia")
                        .WithMany("Shares")
                        .HasForeignKey("SocialMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreFMS.Entities.User", "User")
                        .WithMany("Shares")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("SocialMedia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreFMS.Entities.User", b =>
                {
                    b.HasOne("CoreFMS.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_user_city");

                    b.HasOne("CoreFMS.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_user_company");

                    b.HasOne("CoreFMS.Entities.Education", "Education")
                        .WithMany("Users")
                        .HasForeignKey("EducationId")
                        .HasConstraintName("fk_user_education");

                    b.HasOne("CoreFMS.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_user_role")
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Education");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreFMS.Entities.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoreFMS.Entities.Comment", b =>
                {
                    b.Navigation("ChildComment");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("CoreFMS.Entities.Company", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoreFMS.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("CoreFMS.Entities.Education", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoreFMS.Entities.Feedback", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Reply");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CoreFMS.Entities.FeedbackSubType", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CoreFMS.Entities.FeedbackType", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CoreFMS.Entities.Product", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CoreFMS.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CoreFMS.Entities.Sector", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CoreFMS.Entities.SocialMedium", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CoreFMS.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DirectedFeedbacks");

                    b.Navigation("Feedbacks");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
